INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Agudaru Ingrid'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Alexe Cristina'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Anton-Aanei Andrei'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(2,2,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Fratiman Razvan Constantin'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Apetrei Sergiu'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(2,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Apopei Andreea'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Atasiei Ana'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Axinte Andrei'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(1,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Azoicai Diana'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Baciu Elena'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Bagiu Cosmin'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(1,2,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Balan Paul'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Baltariu Ionut'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Bereanu Cristian'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Boamba Elena'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,2,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Boicu Maria'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Bostan Elena'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(1,1,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Braha Bianca'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Budeanu Radu'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Bulgaru Alexandru'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Butnaru Silviu'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Carnareasa Iulian'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Chelaru Lucian'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Chiriac Alexandra'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,2,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Ciubotariu Andreea Denisa'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Cocea George'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Colac Madalina'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(1,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Croitoru David'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(2,1,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Cojocariu Bogdan'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Damoc Ioana-Beatrice'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(2,1,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Cojocaru Cosmin'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Dandu Adriana Mihaela'));
INSERT into dosare (nr_avertismente, nr_referate, status, id_student)
VALUES(0,0,'Cazat',(SELECT id_student FROM studenti WHERE nume_student='Deaconu Gavrila'));

commit work;
